FinalExam/Areas/Admin/Controllers/BlogController.cs
using FinalExam.Areas.Admin.ViewModels.Blog;
using FinalExam.DAL;
using FinalExam.Models;
using FinalExam.Utulities.Extentions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.ContentModel;
using System.Reflection.Metadata;
using System.Xml.Linq;

namespace FinalExam.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class BlogController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public BlogController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public async Task<IActionResult> Index()
        {
            List<Blog> blogs = await _context.Blogs.ToListAsync();
            return View(blogs);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateBlogVM create)
        {
            if (!ModelState.IsValid) return BadRequest();
            bool result = await _context.Blogs.AnyAsync(x => x.Name.Trim().ToLower() == create.Name.Trim().ToLower());

            if (result)
            {
                ModelState.AddModelError("Name", "This Name Does Exist");
                return View(create);
            }
            if (!create.Photo.ValidateType())
            {

                ModelState.AddModelError("Photo", "Not Valid Type");
                return View(create);
            }
            if (!create.Photo.ValidateSize(10))
            {

                ModelState.AddModelError("Photo", "Max 10mb");
                return View(create);
            }
            Blog blog = new()
            {
                Name = create.Name,
                Description = create.Description,
                Title = create.Title,
                Image = await create.Photo.CreateFile(_env.WebRootPath, "assets", "images","blog")
            };
            await _context.Blogs.AddAsync(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Blog blog = await _context.Blogs.FirstOrDefaultAsync(x => x.Id == id);

            UpdateBlogVM updateBlogVM = new UpdateBlogVM()
            {
                Name = blog.Name,
                Description = blog.Description,
                Title = blog.Title,
                Image = blog.Image,
            };

            return View(updateBlogVM);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateBlogVM update)
        {
            if (!ModelState.IsValid) return BadRequest();
            Blog blogs = _context.Blogs.FirstOrDefault(s => s.Id == id);
            if (blogs is null)
            {
                return NotFound();
            }
            if (update.Photo is not null)
            {
                if (!update.Photo.ValidateType())
                {
                    ModelState.AddModelError("Photo", "Type not valid");
                    return View(update);
                }
                if (!update.Photo.ValidateSize(10))
                {
                    ModelState.AddModelError("Photo", "max 10mb");
                    return View(update);
                }
                blogs.Image.DeleteFile(_env.WebRootPath, "assets", "images", "blog");
                blogs.Image = await update.Photo.CreateFile(_env.WebRootPath, "assets", "images", "blog");

            }
            blogs.Name = update.Name;
            blogs.Description = update.Description;
            blogs.Title = update.Title;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            Blog blogs = _context.Blogs.FirstOrDefault(s => s.Id == id);
            if (blogs is null) return NotFound();

            _context.Remove(blogs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

FinalExam/Areas/Admin/Controllers/SettingController.cs
using FinalExam.Areas.Admin.ViewModels.Blog;
using FinalExam.Areas.Admin.ViewModels.Settings;
using FinalExam.DAL;
using FinalExam.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalExam.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class SettingController : Controller
    {
        private readonly AppDbContext _context;

        public SettingController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Setting> setings = await _context.Settings.ToListAsync();
            return View(setings);
        }
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Setting existed = await _context.Settings.FirstOrDefaultAsync(s => s.Id == id);
            if (existed is null) return NotFound();
            UpdateSettingsVM vm = new()
            {
                Key = existed.Key,
                Value = existed.Value,
            };
            return View(vm);

        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateSettingsVM vm)
        {
            if (!ModelState.IsValid) return View(vm);
            Setting existed = await _context.Settings.FirstOrDefaultAsync(s => s.Id == id);
            if (existed is null) return NotFound();
            existed.Key = vm.Key;
            existed.Value = vm.Value;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
    }
}

FinalExam/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Majestic Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/admin/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/admin/vendors/base/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="~/admin/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/admin/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/admin/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex justify-content-center">
                <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
                    <a class="navbar-brand brand-logo" href="index.html"><img src="~/admin/images/logo.svg" alt="logo" /></a>
                    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/admin/images/logo-mini.svg" alt="logo" /></a>
                    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                        <span class="mdi mdi-sort-variant"></span>
                    </button>
                </div>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <ul class="navbar-nav mr-lg-4 w-100">
                    <li class="nav-item nav-search d-none d-lg-block w-100">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="search">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" placeholder="Search now" aria-label="search" aria-describedby="search">
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-nav-right">
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Home" class="btn btn-inverse"> <i class="btn btn-inverse-info">Home</i></a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Blog" class="btn btn-inverse"> <i class="btn btn-inverse-info">Blog</i></a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Setting" class="btn btn-inverse"> <i class="btn btn-inverse-info">Settings</i></a>
                    </li>
                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel">
                @RenderBody()
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/admin/vendors/base/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <script src="~/admin/vendors/chart.js/Chart.min.js"></script>
    <script src="~/admin/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/admin/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/admin/js/off-canvas.js"></script>
    <script src="~/admin/js/hoverable-collapse.js"></script>
    <script src="~/admin/js/template.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/admin/js/dashboard.js"></script>
    <script src="~/admin/js/data-table.js"></script>
    <script src="~/admin/js/jquery.dataTables.js"></script>
    <script src="~/admin/js/dataTables.bootstrap4.js"></script>
    <!-- End custom js for this page-->

    <script src="~/admin/js/jquery.cookie.js" type="text/javascript"></script>
</body>

</html>